Clear-Host
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host "######################################################################"
Write-Host "#     Grab a tea or coffee, this could take a bit...                 #"
Write-Host "######################################################################"
Write-Host "#                                                                    #"
Write-Host "#                         (  )   (   )  )                            #"
Write-Host "#                          ) (   )  (  (                             #"
Write-Host "#                          ( )  (    ) )                             #"
Write-Host "#                          _____________                             #"
Write-Host "#                         ^|_____________^| ___                      #"
Write-Host "#                         ^|             ^|/ _ \                     #"
Write-Host "#                         ^|               ^| ^| ^|                  #"
Write-Host "#                         ^|     EPI       ^|_^| ^|                  #"
Write-Host "#                      ___^|             ^|\___/                     #"
Write-Host "#                     /    \___________/    \                        #"
Write-Host "#                     \_____________________/                        #"
Write-Host "#                                                                    #"
Write-Host "######################################################################"